import {SummaryCourtSheet} from "./SummaryCourtSheet";
import {useChatUnread} from "./ChatMessageIndicator";
import {useEffect,useRef,useState} from "react";
import {supabase} from "../lib/supabase";
import {staffApi,type Context} from "../lib/staffApi";
const labels={request:"Request",players:"Players",date:"Date",time:"Time",location:"Location(s)",pro:"Pro (optional)",court:"Court (optional)",questions:"Outstanding questions"};
type Draft=Record<keyof typeof labels,string>;
const empty:Draft={request:"",players:"",date:"",time:"",location:"",pro:"",court:"",questions:""};
type Shared={id:string;sender_name:string;details:Draft;created_at:string};
export function SummaryComposer({context:p,threadId,onClose}:{context:Context;threadId:string;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[draft,setDraft]=useState<Draft>(empty),[editing,setEditing]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(""),[sent,setSent]=useState(false);
 const pending=useRef(false),attempt=useRef<{id:string;text:string}|null>(null);
 useEffect(()=>{dialog.current?.showModal();const c=new AbortController();void staffApi<{draft:Draft}>(p,`/member-conversations/${threadId}/draft-summary?club_id=${encodeURIComponent(p.clubId)}`,"POST",{},c.signal).then(d=>{if(!c.signal.aborted){setDraft(d.draft);setError("");}}).catch(e=>{if(!c.signal.aborted){setError(e.message);setEditing(true);}}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[threadId,p.clubId,p.userId]);
 async function send(){if(pending.current||!draft.request.trim())return;pending.current=true;setBusy(true);setError("");const text=JSON.stringify(draft);if(attempt.current?.text!==text)attempt.current={id:crypto.randomUUID(),text};try{const auth=await supabase.auth.getSession();if(auth.data.session?.user.id!==p.userId)throw new Error("Sign in again.");const {data,error}=await supabase.rpc("member_chat_summary",{p_club:p.clubId,p_action:"send",p_thread:threadId,p_id:attempt.current.id,p_details:draft});if(error||data?.id!==attempt.current.id||!data?.sent)throw new Error("Sending could not be confirmed. Retry the unchanged draft to avoid a duplicate.");setSent(true);}catch(e){setError((e as Error).message);}finally{pending.current=false;setBusy(false);}}
 return <dialog ref={dialog} className="conversation-summary-dialog" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><h3>{sent?"Summary sent":"Review summary"}</h3>{sent?<><p>Front Desk and Manager can now see this summary. It does not confirm a booking.</p><button onClick={onClose}>Done</button></>:<><p>Based on the latest 100 messages. Check every detail. Only this reviewed summary goes to Front Desk and Manager; your private chat stays private.</p>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">{pending.current?"Sending summary…":"Preparing draft…"}</p>}<div>{(Object.keys(labels) as (keyof Draft)[]).map(k=>editing?<label key={k}>{labels[k]}<textarea maxLength={1000} disabled={busy} value={draft[k]} onChange={e=>setDraft(v=>({...v,[k]:e.target.value}))}/></label>:<p key={k}><strong>{labels[k]}:</strong> {draft[k]||"Not specified"}</p>)}</div><footer><button disabled={busy} onClick={onClose}>Cancel</button><button disabled={busy} onClick={()=>setEditing(v=>!v)}>{editing?"Review":"Edit"}</button><button disabled={busy||editing||!draft.request.trim()} onClick={()=>void send()}>Send to staff</button></footer></>}</dialog>;
}
export function StaffConversations({context:p}:{context:Context}){
 const unread=useChatUnread(p.clubId,p.userId,true);
 const [expanded,setExpanded]=useState<string|null>(null);
 async function openSummary(id:string){setExpanded(v=>v===id?null:id);const {error}=await supabase.rpc("staff_summary_unread",{p_club:p.clubId,p_id:id});if(!error)window.dispatchEvent(new Event("chat-read"));}

 const [rows,setRows]=useState<Shared[]>([]),[error,setError]=useState(""),[offset,setOffset]=useState(0),[more,setMore]=useState(false);
 useEffect(()=>{if(!["manager","front_desk"].includes(p.role))return;let stopped=false,running=false;setRows([]);async function load(){if(running)return;running=true;try{const auth=await supabase.auth.getSession();if(auth.data.session?.user.id!==p.userId)throw new Error("Sign in again.");const {data,error}=await supabase.rpc("member_chat_summary",{p_club:p.clubId,p_action:"inbox",p_offset:offset});if(error)throw new Error("Summaries could not be loaded. Check that the conversations database update is installed.");if(!stopped){setRows(data.slice(0,25));setMore(data.length>25);setError("");}}catch(e){if(!stopped)setError((e as Error).message);}finally{running=false;}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},10000);return()=>{stopped=true;clearInterval(timer);};},[p.clubId,p.userId,p.role,offset]);
 if(!["manager","front_desk"].includes(p.role))return null;
 return <section className="member-chat"><h3>Conversations</h3><p>Member-reviewed summaries shared with Front Desk and Manager. These are requests, not confirmed bookings. Updates every 10 seconds.</p>{error&&<p role="alert">{error}</p>}{!rows.length&&!error&&<p>No shared summaries.</p>}{rows.map(r=><article key={r.id}><h4>Shared by {r.sender_name} {unread.includes(r.id)&&<span className="request-unread-dot" role="img" aria-label="Unread summary"/>}</h4><time>{new Date(r.created_at).toLocaleString()}</time>{(Object.keys(labels) as (keyof Draft)[]).filter(k=>r.details[k]).map(k=><p key={k}><strong>{labels[k]}:</strong> {r.details[k]}</p>)}<button onClick={()=>void openSummary(r.id)}>{expanded===r.id?"Close court sheet":"View summary / court sheet"}</button>{expanded===r.id&&<SummaryCourtSheet context={p} summary={r}/>}</article>)}<button disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-25))}>Previous</button><button disabled={!more} onClick={()=>setOffset(v=>v+25)}>Next</button></section>;
}
