import {SummaryComposer} from "./ConversationSummary";
import {useEffect,useRef,useState} from "react";
import {supabase} from "../lib/supabase";
import "./MemberChat.css";
type Person={id:string;name:string;is_creator?:boolean};
type Message={id:string;body:string;created_at:string;mine:boolean;sender_name?:string};
export function MemberChat(p:{clubId:string;userId:string;role:string;apiBase:string}){
 const [threads,setThreads]=useState<Person[]>([]),[search,setSearch]=useState(""),[people,setPeople]=useState<Person[]>([]),[active,setActive]=useState<Person|null>(null),[messages,setMessages]=useState<Message[]>([]),[body,setBody]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [mode,setMode]=useState<"create"|"join"|null>(null),[title,setTitle]=useState(""),[selected,setSelected]=useState<Person[]>([]),[joinCode,setJoinCode]=useState(""),[secret,setSecret]=useState(""),[participants,setParticipants]=useState<Person[]>([]);
 const [peoplePage,setPeoplePage]=useState(0),[peopleMore,setPeopleMore]=useState(false),[peopleLoading,setPeopleLoading]=useState(false),[peopleError,setPeopleError]=useState("");
 const [memberEmails,setMemberEmails]=useState<Record<string,string>>({});
 const roomAttempt=useRef<{key:string;id:string}|null>(null),roomPending=useRef(false);
 async function room(action:string,extra:Record<string,unknown>={}){const auth=await supabase.auth.getSession();if(auth.data.session?.user.id!==p.userId)throw new Error("Sign in again.");const {data,error}=await supabase.rpc("member_chat_room",{p_club:p.clubId,p_action:action,...extra});if(error)throw new Error(error.code==="P0001"?error.message:error.code==="42501"?"Room unavailable, invalid code, or access denied.":"The room could not be confirmed. Check the chat-room update is installed, then retry.");return data;}
 function choose(t:Person){setActive(t);setBody("");setSecret("");setParticipants([]);attempt.current=null;}
 async function createRoom(){if(roomPending.current)return;roomPending.current=true;setBusy(true);const key=JSON.stringify([title.trim(),selected.map(v=>[v.id,(memberEmails[v.id]??"").trim().toLowerCase()]).sort()]);if(roomAttempt.current?.key!==key)roomAttempt.current={key,id:crypto.randomUUID()};try{const t=await room("create",{p_thread:roomAttempt.current.id,p_title:title.trim(),p_members:selected.map(v=>v.id),p_emails:Object.fromEntries(selected.map(v=>[v.id,(memberEmails[v.id]??"").trim()]))});choose(t);setThreads(await call("list"));setMode(null);setTitle("");setSelected([]);setMemberEmails({});setSearch("");roomAttempt.current=null;setError("");}catch(e){setError((e as Error).message);}finally{roomPending.current=false;setBusy(false);}}
 async function joinRoom(){if(roomPending.current)return;roomPending.current=true;setBusy(true);try{const t=await room("join",{p_code:joinCode.trim()});choose(t);setJoinCode("");setThreads(await call("list"));setMode(null);setError("");}catch(e){setError((e as Error).message);}finally{roomPending.current=false;setBusy(false);}}
 async function showCode(){if(!active)return;setBusy(true);try{const data=await room("code",{p_thread:active.id});setSecret(data.code);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const [summaryOpen,setSummaryOpen]=useState(false);
 const [shared,setShared]=useState<{id:string;sender_name:string;created_at:string}[]>([]);
 useEffect(()=>{setShared([]);if(!active||summaryOpen)return;let cancelled=false;async function load(){const {data,error}=await supabase.rpc("member_chat_summary",{p_club:p.clubId,p_action:"sent",p_thread:active!.id});if(!cancelled&&!error)setShared(data);}void load();const timer=setInterval(()=>void load(),10000);return()=>{cancelled=true;clearInterval(timer);};},[active?.id,summaryOpen,p.clubId]);
 const sending=useRef(false),attempt=useRef<{body:string;id:string}|null>(null);
 async function call(action:string,extra:Record<string,unknown>={}){const auth=await supabase.auth.getSession();if(auth.error||auth.data.session?.user.id!==p.userId)throw new Error("Please sign in again.");const {data,error}=await supabase.rpc("member_chat",{p_club:p.clubId,p_action:action,...extra});if(error)throw new Error(error.code==="42501"?"You do not have access to this conversation.":"Conversations are unavailable. Please try again after the chat update is installed.");return data;}
 useEffect(()=>{if(p.role!=="member")return;let stopped=false,running=false;async function load(){if(running)return;running=true;try{const rows=await call("list");if(!stopped)setThreads(rows);}catch(e){if(!stopped)setError((e as Error).message);}finally{running=false;}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},10000);return()=>{stopped=true;clearInterval(timer);};},[p.clubId,p.userId,p.role]);
 useEffect(()=>{setPeople([]);setPeopleMore(false);setPeopleError("");if(mode!=="create"||p.role!=="member")return;let stopped=false;setPeopleLoading(true);const timer=setTimeout(()=>{void(async()=>{try{const auth=await supabase.auth.getSession();if(auth.data.session?.user.id!==p.userId)throw new Error("Sign in again.");const {data,error}=await supabase.rpc("chat_member_directory",{p_club:p.clubId,p_search:search.trim(),p_offset:peoplePage});if(error||!Array.isArray(data))throw new Error("Member list is unavailable. Check that the member-directory update is installed, then reopen Create new chat.");if(!stopped){setPeople(data.slice(0,30));setPeopleMore(data.length>30);}}catch(e){if(!stopped)setPeopleError((e as Error).message);}finally{if(!stopped)setPeopleLoading(false);}})();},200);return()=>{stopped=true;clearTimeout(timer);};},[mode,search,peoplePage,p.clubId,p.userId,p.role]);
 useEffect(()=>{setMessages([]);if(!active)return;let stopped=false,running=false;async function load(){if(running||sending.current)return;running=true;try{const data=await call("read",{p_thread:active!.id});if(!stopped){setMessages(data.messages);setParticipants(data.participants??[]);setError("");}}catch(e){if(!stopped)setError((e as Error).message);}finally{running=false;}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},5000);return()=>{stopped=true;clearInterval(timer);};},[active?.id,p.clubId,p.userId]);
 async function send(){const text=body.trim();if(!active||!text||sending.current)return;sending.current=true;setBusy(true);if(attempt.current?.body!==text)attempt.current={body:text,id:crypto.randomUUID()};try{const row=await call("send",{p_thread:active.id,p_body:text,p_message:attempt.current.id});setMessages(row.messages);setBody("");attempt.current=null;setError("");}catch(e){setError((e as Error).message);}finally{sending.current=false;setBusy(false);}}
 if(p.role!=="member")return null;
 return <section className="member-chat"><h3>Chat Room</h3><p>Private rooms for members of your club. Everyone added or joining can read the room history. Any participant can choose Send summary to create an AI draft from the latest messages, review or edit it, and send only that summary to Front Desk and Manager. Generating a draft sends those messages to our AI provider. Nothing is shared with staff until you confirm.</p>{error&&<p role="alert">{error}</p>}<div className="member-chat-columns"><aside><button disabled={busy} onClick={()=>{setMode("create");setPeoplePage(0);setSecret("");}}>Create new chat</button><button disabled={busy} onClick={()=>{setMode("join");setSecret("");}}>Join Chat Room</button>
 {mode==="create"&&<form onSubmit={e=>{e.preventDefault();void createRoom();}}><label>Chat room name<input required maxLength={80} value={title} disabled={busy} onChange={e=>setTitle(e.target.value)}/></label><label>Add fellow members<input value={search} disabled={busy} maxLength={100} onChange={e=>{setSearch(e.target.value);setPeoplePage(0);}} placeholder="Search members or browse below"/></label><p>{selected.length} members selected</p>{peopleLoading&&<p role="status">Loading members…</p>}{peopleError&&<p role="alert">{peopleError}</p>}<div className="chat-member-picker" aria-label="Available club members">{people.map(person=>{const checked=selected.some(v=>v.id===person.id);return <label className="chat-member-option" key={person.id}><input type="checkbox" checked={checked} disabled={busy||(!checked&&selected.length>=49)} onChange={()=>setSelected(v=>checked?v.filter(x=>x.id!==person.id):[...v,person])}/><span>{person.name}</span></label>;})}{!peopleLoading&&!peopleError&&!people.length&&<p>No eligible members found.</p>}</div><div className="chat-member-pages"><button type="button" disabled={busy||peopleLoading||peoplePage===0} onClick={()=>setPeoplePage(v=>Math.max(0,v-30))}>Previous</button><span>Page {peoplePage/30+1}</span><button type="button" disabled={busy||peopleLoading||!peopleMore} onClick={()=>setPeoplePage(v=>v+30)}>Next</button></div>{selected.map(person=><div key={person.id} className="chat-member-verification"><label>Email for {person.name}<input type="email" required maxLength={320} autoComplete="off" disabled={busy} value={memberEmails[person.id]??""} onChange={e=>setMemberEmails(v=>({...v,[person.id]:e.target.value}))} placeholder="Enter their member-profile email"/></label><button type="button" disabled={busy} onClick={()=>{setSelected(v=>v.filter(x=>x.id!==person.id));setMemberEmails(v=>{const next={...v};delete next[person.id];return next;});}}>Remove {person.name}</button></div>)}<p>Each selected member’s email must match their club profile before the chat can be created. Emails are checked privately and are not shown to other members.</p><small>You can add members now or invite them privately using your room code. Up to 50 members per room.</small><button disabled={busy||!title.trim()||selected.some(person=>!memberEmails[person.id]?.trim())}>Create chat</button><button type="button" disabled={busy} onClick={()=>setMode(null)}>Cancel</button></form>}
 {mode==="join"&&<form onSubmit={e=>{e.preventDefault();void joinRoom();}}><label>Secret room code<input type="password" autoComplete="off" maxLength={80} required value={joinCode} disabled={busy} onChange={e=>setJoinCode(e.target.value)}/></label><p>Ask the original creator for the code. Joining gives access to the room history.</p><button disabled={busy||!joinCode.trim()}>Join</button><button type="button" disabled={busy} onClick={()=>{setMode(null);setJoinCode("");}}>Cancel</button></form>}
 <h4>Your chat rooms</h4><small>Showing your 100 most recent rooms and conversations.</small>{threads.map(t=><button disabled={busy} key={t.id} aria-pressed={active?.id===t.id} onClick={()=>choose(t)}>{t.name}</button>)}</aside><div>{active?<><h4>{active.name}</h4>{participants.length>0&&<p>Members: {participants.map(v=>v.name).join(", ")}</p>}{active.is_creator&&<div><button disabled={busy} onClick={()=>{if(secret)setSecret("");else void showCode();}}>{secret?"Hide secret code":"View secret code"}</button>{secret&&<p className="room-secret"><strong>{secret}</strong><br/>Only you, the original creator, can view this code here. Share it privately with members you want to invite.</p>}</div>}<button disabled={busy||!messages.length} onClick={()=>setSummaryOpen(true)}>Send summary</button>{shared.map(s=><p key={s.id}>Summary shared with Front Desk and Manager by {s.sender_name} · {new Date(s.created_at).toLocaleString()}</p>)}<div className="member-chat-history" aria-label="Messages">{messages.length===100&&<p>Showing the latest 100 messages.</p>}{messages.map(m=><article key={m.id} className={m.mine?"mine":""}><strong>{m.mine?"You":m.sender_name||active.name}</strong><time>{new Date(m.created_at).toLocaleString()}</time><p>{m.body}</p></article>)}{!messages.length&&<p>No messages yet.</p>}</div><form onSubmit={e=>{e.preventDefault();void send();}}><label>Message<textarea maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} disabled={busy}/></label><button disabled={busy||!body.trim()}>{busy?"Sending…":"Send message"}</button></form></>:<p>Create a new chat, join with a secret code, or choose one of your rooms.</p>}</div></div>{summaryOpen&&active&&<SummaryComposer context={p} threadId={active.id} onClose={()=>setSummaryOpen(false)}/>}</section>;
}
