import {useEffect,useRef,useState} from 'react';
import {loadStripe,type Stripe,type StripeElements} from '@stripe/stripe-js';
import {staffApi,type Context} from '../lib/staffApi';
type Pending={id:string;amount_cents:number;status:string;reason:string};
export function MemberPaymentRecovery(p:Context){
 const [rows,setRows]=useState<Pending[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[revision,setRevision]=useState(0);
 const mount=useRef<HTMLDivElement>(null),stripe=useRef<Stripe|null>(null),elements=useRef<StripeElements|null>(null),lock=useRef(false);
 const query=`?club_id=${encodeURIComponent(p.clubId)}`;
 useEffect(()=>{const c=new AbortController();void staffApi<{payments:Pending[]}>(p,'/payments/member/pending'+query,'GET',undefined,c.signal).then(r=>{if(!c.signal.aborted)setRows(r.payments);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[p.userId,p.clubId,revision,query]);
 useEffect(()=>{if(!selected)return;let canceled=false;const c=new AbortController();setReady(false);setError('');elements.current=null;stripe.current=null;
 void(async()=>{try{const r=await staffApi<{client_secret?:string;publishable_key:string;account_id:string}>(p,`/payments/member/payments/${selected}/confirm${query}`,'GET',undefined,c.signal);if(canceled)return;if(!r.client_secret){setSelected('');setRevision(v=>v+1);return;}const s=await loadStripe(r.publishable_key,{stripeAccount:r.account_id});if(!s||canceled||!mount.current)return;const el=s.elements({clientSecret:r.client_secret});const widget=el.create('payment');widget.mount(mount.current);elements.current=el;stripe.current=s;widget.on('ready',()=>{if(!canceled)setReady(true);});}catch(e){if(!canceled)setError(e instanceof Error?e.message:'Unable to open secure payment form.');}})();
 return()=>{canceled=true;c.abort();elements.current?.getElement('payment')?.destroy();elements.current=null;stripe.current=null;};},[selected,p.userId,p.clubId,query]);
 async function confirm(){if(lock.current||!stripe.current||!elements.current)return;lock.current=true;setBusy(true);try{const r=await stripe.current.confirmPayment({elements:elements.current,confirmParams:{return_url:location.origin+'/?payment_setup=returned'},redirect:'if_required'});if(r.error)setError(r.error.message||'Payment could not be completed.');else{await staffApi(p,`/payments/member/payments/${selected}/confirm${query}`);setSelected('');setRevision(v=>v+1);setError('Payment submitted. Its final status is verified with Stripe.');}}catch(e){setError(e instanceof Error?e.message:'Refresh to verify the payment.');}finally{setBusy(false);lock.current=false;}}
 return <section><h4>Payments needing your attention</h4>{rows.length===0&&<p>No pending card confirmations.</p>}{rows.map(r=><p key={r.id}>{r.reason} · ${(r.amount_cents/100).toFixed(2)} · {r.status.replaceAll('_',' ')} <button disabled={busy} onClick={()=>setSelected(r.id)}>Review payment</button></p>)}{selected&&<><div ref={mount}/><button disabled={busy||!ready} onClick={()=>void confirm()}>Confirm payment</button></>}{error&&<p role="status">{error}</p>}<button disabled={busy} onClick={()=>setRevision(v=>v+1)}>Refresh pending payments</button></section>;
}
