import {useEffect,useMemo,useRef,useState} from "react";
import {supabase} from "../lib/supabase";
import {staffApi,type Context} from "../lib/staffApi";
import {locationTimeToIso} from "../lib/createActions";
import QuickCreate from "./QuickCreate";
import "./SummaryCourtSheet.css";
type Details=Record<string,string>;
type Location={id:string;name:string;timezone:string;opening_time:string;closing_time:string};
type Window={starts_at:string;ends_at:string};
type Court={id:string;name:string;court_number?:number};
type Pro={id:string;first_name:string;last_name:string};
type Availability={court_availability:{court:Court;free_windows:Window[];bookings:Window[]}[];pro_availability:{pro:Pro;free_windows:Window[];max_lessons_reached:boolean;required_break_minutes:number;bookings:Window[]}[]};
type Proposal={id:string;summary_id:string;status:string;can_accept?:boolean;details:Details&{input:Record<string,string>};created_at:string};
const covers=(windows:Window[],start:string,end:string)=>windows.some(w=>Date.parse(w.starts_at)<=Date.parse(start)&&Date.parse(w.ends_at)>=Date.parse(end));
const clock=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
const minutes=(time:string)=>Number(time.slice(0,2))*60+Number(time.slice(3,5));
async function rpc(p:Context,action:string,extra:Record<string,unknown>){const auth=await supabase.auth.getSession();if(auth.data.session?.user.id!==p.userId)throw new Error("Sign in again.");const {data,error}=await supabase.rpc("chat_booking_proposal",{p_club:p.clubId,p_action:action,...extra});if(error)throw new Error(error.code==="42501"?"You do not have access to this proposal.":error.message);return data;}
export function SummaryCourtSheet({context:p,summary}:{context:Context;summary:{id:string;details:Details}}){
 const [locations,setLocations]=useState<Location[]>([]),[locationId,setLocationId]=useState(""),[day,setDay]=useState(/^\d{4}-\d{2}-\d{2}$/.test(summary.details.date)?summary.details.date:""),[duration,setDuration]=useState(60),[proId,setProId]=useState(""),[placement,setPlacement]=useState<{courtId:string;minute:number}|null>(null),[note,setNote]=useState("");
 const [loadedFor,setLoadedFor]=useState("");
 const [availability,setAvailability]=useState<Availability|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[proposals,setProposals]=useState<Proposal[]>([]),[createBooking,setCreateBooking]=useState(false),[version,setVersion]=useState(0);
 const [responseIntro,setResponseIntro]=useState(""),[draftSource,setDraftSource]=useState("");
 const attempt=useRef<{key:string;id:string}|null>(null),pending=useRef(false);
 const location=locations.find(l=>l.id===locationId),zone=location?.timezone||"UTC";
 useEffect(()=>{const c=new AbortController();void staffApi<{locations:Location[]}>(p,`/locations?club_id=${p.clubId}`,"GET",undefined,c.signal).then(data=>{setLocations(data.locations);const matches=data.locations.filter(l=>l.name.toLowerCase()===summary.details.location?.trim().toLowerCase());if(matches.length===1)setLocationId(matches[0].id);else if(data.locations.length===1)setLocationId(data.locations[0].id);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[p.clubId,p.userId]);
 useEffect(()=>{let stopped=false;async function load(){try{const rows=await rpc(p,"list",{p_summary:summary.id});if(!stopped)setProposals(rows);}catch(e){if(!stopped)setError((e as Error).message);}}void load();const t=setInterval(()=>void load(),10000);return()=>{stopped=true;clearInterval(t);};},[summary.id,p.clubId,p.userId,version]);
 useEffect(()=>{setAvailability(null);setLoadedFor("");setReview(false);if(!day||!locationId)return;const c=new AbortController();async function load(){try{const data=await staffApi<Availability>(p,`/availability?location_id=${locationId}&availability_date=${day}`,"GET",undefined,c.signal);if(!c.signal.aborted){setAvailability(data);setLoadedFor(`${locationId}:${day}`);setError("");}}catch(e){if(!c.signal.aborted){setAvailability(null);setError((e as Error).message);}}}void load();const t=setInterval(()=>void load(),15000);return()=>{c.abort();clearInterval(t);};},[day,locationId,p.clubId,p.userId,version]);
 const timeCache=useMemo(()=>new Map<number,{start:string;end:string}>(),[day,duration,zone]);
 function times(minute:number){const cached=timeCache.get(minute);if(cached)return cached;const start=locationTimeToIso(`${day}T${clock(minute)}`,zone);const value={start,end:new Date(Date.parse(start)+duration*60000).toISOString()};timeCache.set(minute,value);return value;}
 function available(courtId:string,minute:number,data=availability){try{const {start,end}=times(minute);if(Date.parse(start)<=Date.now()||!data)return false;const court=data.court_availability.find(c=>c.court.id===courtId);if(!court||!covers(court.free_windows,start,end))return false;if(proId){const pro=data.pro_availability.find(v=>v.pro.id===proId);if(!pro||pro.max_lessons_reached||!covers(pro.free_windows,start,end))return false;const gap=pro.required_break_minutes*60000;if(pro.bookings.some(b=>Date.parse(b.starts_at)-gap<Date.parse(end)&&Date.parse(b.ends_at)+gap>Date.parse(start)))return false;}return true;}catch{return false;}}
 function place(courtId:string,minute:number){if(busy||!available(courtId,minute))return;setPlacement({courtId,minute});setReview(false);}
 const startMinute=location?Math.ceil(minutes(location.opening_time)/15)*15:0,endMinute=location?minutes(location.closing_time):0;
 const slots=Array.from({length:Math.max(0,Math.ceil((endMinute-startMinute)/15))},(_,i)=>startMinute+i*15);
 const selectedCourt=availability?.court_availability.find(c=>c.court.id===placement?.courtId)?.court,selectedPro=availability?.pro_availability.find(v=>v.pro.id===proId)?.pro;
 const response=placement&&location?`Updated response\n${summary.details.request}\nPlayers: ${summary.details.players||"Please confirm"}\nDate: ${day}\nTime: ${clock(placement.minute)}–${clock(placement.minute+duration)} (${zone})\nLocation: ${location.name}\nCourt: ${selectedCourt?.court_number??""} ${selectedCourt?.name??""}\nPro: ${selectedPro?[selectedPro.first_name,selectedPro.last_name].join(" "):"Unassigned"}\n${note}\nProposal only. No court is reserved.`:"";
 async function prepare(){if(!placement||pending.current)return;pending.current=true;setBusy(true);setError("");try{const {start,end}=times(placement.minute);const data=await staffApi<{message:string;generated_with:string}>(p,`/conversation-summaries/${summary.id}/draft-response?club_id=${p.clubId}`,"POST",{location_id:locationId,court_id:placement.courtId,pro_id:proId||null,starts_at:start,ends_at:end,note});setResponseIntro(data.message);setDraftSource(data.generated_with);setReview(true);}catch(e){setError((e as Error).message);}finally{pending.current=false;setBusy(false);}}
 async function send(){if(!placement||!location||pending.current)return;pending.current=true;setBusy(true);setError("");try{const fresh=await staffApi<Availability>(p,`/availability?location_id=${locationId}&availability_date=${day}`);setAvailability(fresh);if(!available(placement.courtId,placement.minute,fresh))throw new Error("That time or pro is no longer available. Choose another slot.");const {start,end}=times(placement.minute);const details={location_id:locationId,court_id:placement.courtId,pro_id:proId,starts_at:start,ends_at:end,note,response_intro:responseIntro};const key=JSON.stringify(details);if(attempt.current?.key!==key)attempt.current={key,id:crypto.randomUUID()};await rpc(p,"send",{p_summary:summary.id,p_id:attempt.current.id,p_details:details});setReview(false);setVersion(v=>v+1);window.dispatchEvent(new Event("chat-read"));}catch(e){setError((e as Error).message);}finally{setBusy(false);pending.current=false;}}
 const latest=proposals[0];
 return <div className="summary-court-sheet"><h4>Proposed booking</h4><p>Requested: {summary.details.date||"Date not specified"} · {summary.details.time||"Time not specified"}. Choose the exact date before placing the block.</p><div className="proposal-controls"><label>Location<select value={locationId} disabled={busy} onChange={e=>{setLocationId(e.target.value);setPlacement(null);setProId("");setReview(false);}}><option value="">Choose location</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Date<input type="date" value={day} disabled={busy} onChange={e=>{setDay(e.target.value);setReview(false);}}/></label><label>Duration (minutes)<select value={duration} disabled={busy} onChange={e=>{setDuration(Number(e.target.value));setReview(false);}}>{[15,30,45,60,75,90,120,180,240].map(n=><option key={n}>{n}</option>)}</select></label><label>Pro<select value={proId} disabled={busy} onChange={e=>{setProId(e.target.value);setReview(false);}}><option value="">Unassigned</option>{availability?.pro_availability.map(v=><option key={v.pro.id} value={v.pro.id}>{v.pro.first_name} {v.pro.last_name}</option>)}</select></label></div>
 {error&&<p role="alert">{error}</p>}{location&&day&&!availability&&!error&&<p>Loading availability…</p>}{availability&&<><p>{zone}. Drag the proposal to a free slot, or tap a slot. Shaded slots are unavailable for the selected duration/pro. Refreshes every 15 seconds.</p><div draggable={!busy} onDragStart={e=>e.dataTransfer.setData("text/plain","booking-proposal")} className="proposal-tray">Drag proposal: {summary.details.request}</div><div className="proposal-scroll"><div className="proposal-grid" style={{gridTemplateColumns:`60px repeat(${availability.court_availability.length},minmax(140px,1fr))`}}><div><strong>Time</strong>{slots.map(m=><div className="proposal-time" key={m}>{clock(m)}</div>)}</div>{availability.court_availability.map(c=><div key={c.court.id}><strong>Court {c.court.court_number} {c.court.name}</strong><div className="proposal-column">{slots.map(m=><button type="button" key={m} className={`proposal-cell ${available(c.court.id,m)?"free":"occupied"}`} aria-label={`${c.court.name}, ${clock(m)}, ${available(c.court.id,m)?"available":"unavailable"}`} disabled={busy||!available(c.court.id,m)} onClick={()=>place(c.court.id,m)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.getData("text/plain")==="booking-proposal")place(c.court.id,m);}}/>)}{placement?.courtId===c.court.id&&<div className="proposal-block" draggable={!busy} onDragStart={e=>e.dataTransfer.setData("text/plain","booking-proposal")} style={{top:(placement.minute-startMinute)/15*24,height:duration/15*24}}><strong>Proposed</strong><span>{clock(placement.minute)}–{clock(placement.minute+duration)}</span><span>{selectedPro?[selectedPro.first_name,selectedPro.last_name].join(" "):"Unassigned"}</span></div>}</div></div>)}</div></div></>}
 <label>Message to members<textarea value={note} maxLength={1000} disabled={busy} onChange={e=>{setNote(e.target.value);setReview(false);}}/></label>{placement&&!available(placement.courtId,placement.minute)&&<p role="alert">This placement is unavailable. Choose another time or pro.</p>}<button disabled={busy||!placement||!available(placement.courtId,placement.minute)} onClick={()=>void prepare()}>Review updated response</button>{review&&<div className="proposal-review"><h4>Updated response</h4><p>{draftSource==="ai"?"AI draft — review before sending.":"Prepared from the scheduling details; AI drafting is unavailable."}</p><label>Response introduction<textarea maxLength={1000} value={responseIntro} disabled={busy} onChange={e=>setResponseIntro(e.target.value)}/></label><p style={{whiteSpace:"pre-wrap"}}>{response}</p><button disabled={busy} onClick={()=>setReview(false)}>Edit</button><button disabled={busy} onClick={()=>void send()}>{busy?"Sending…":"Send to original chat room"}</button></div>}
 {latest&&<div><h4>Latest sent proposal: {latest.status.replaceAll("_"," ")}</h4><p>{latest.details.date} · {latest.details.time} · {latest.details.location} · {latest.details.court} · {latest.details.pro}</p>{latest.status==="accepted"&&<><p>The requesting member accepted. Complete the booking with verified participants and pricing; availability will be checked again.</p><button onClick={()=>{const input=latest.details.input;setLocationId(input.location_id);setDay(latest.details.date);setCreateBooking(true);}}>Complete accepted booking</button></>}</div>}
 {createBooking&&latest&&location&&loadedFor===`${latest.details.input.location_id}:${latest.details.date}`&&locationId===latest.details.input.location_id&&<QuickCreate proposalId={latest.id} lockProposal kind="booking" apiBase={p.apiBase} clubId={p.clubId} role={p.role} userId={p.userId} locationId={locationId} locationName={location.name} timeZone={zone} date={latest.details.date} courts={(availability?.court_availability||[]).map(c=>({...c.court,location_id:locationId}))} initialProId={latest.details.input.pro_id} initialRange={{courtId:latest.details.input.court_id,start:`${latest.details.date}T${latest.details.time.slice(0,5)}`,end:`${latest.details.date}T${latest.details.time.slice(6,11)}`}} onClose={()=>setCreateBooking(false)} onCreated={()=>{setCreateBooking(false);setVersion(v=>v+1);setError("Booking confirmed and the chat room notified.");}}/>}
 </div>;
}
export function MemberProposalResponses({context:p,threadId}:{context:Context;threadId:string}){
 const [rows,setRows]=useState<Proposal[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{let stopped=false;async function load(){try{const rows=await rpc(p,"list",{p_thread:threadId});if(!stopped)setRows(rows);}catch(e){if(!stopped)setError((e as Error).message);}}void load();const t=setInterval(()=>void load(),10000);return()=>{stopped=true;clearInterval(t);};},[threadId,p.clubId,p.userId,version]);
 async function respond(row:Proposal,action:string){if(busy)return;setBusy(true);try{await rpc(p,action,{p_summary:row.summary_id,p_id:row.id});setError("");setVersion(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div>{error&&<p role="alert">{error}</p>}{rows.map(row=><article key={row.id}><h4>Updated response from staff · {row.status.replaceAll("_"," ")}</h4>{row.details.response_intro&&<p>{row.details.response_intro}</p>}<p>{row.details.request}</p><p>Players: {row.details.players}</p><p>{row.details.date} · {row.details.time} ({row.details.timezone})</p><p>{row.details.location} · Court {row.details.court} · Pro: {row.details.pro}</p>{row.details.note&&<p>{row.details.note}</p>}{row.status!=="booked"&&<p>Proposal only. Acceptance tells staff to complete the booking; it does not reserve the court yet.</p>}{row.status==="proposed"&&row.can_accept&&<><button disabled={busy} onClick={()=>void respond(row,"accept")}>Accept proposal</button><button disabled={busy} onClick={()=>void respond(row,"changes")}>Request changes</button></>}{row.status==="proposed"&&!row.can_accept&&<p>The member who shared the summary can accept or request changes.</p>}</article>)}</div>;
}
